const REWARD_CLAIM_REASONS = Object.freeze({
  TIER_NOT_ELIGIBLE: "TIER_NOT_ELIGIBLE",
  INSUFFICIENT_POINTS: "INSUFFICIENT_POINTS",
  CLAIM_LIMIT_REACHED: "CLAIM_LIMIT_REACHED",
  REWARD_EXPIRED: "REWARD_EXPIRED",
  REWARD_INACTIVE: "REWARD_INACTIVE",
});

module.exports = REWARD_CLAIM_REASONS;
