name: Deploy Node.js API to Azure Web App - Pleis-backend-dev

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: true
        with:
          app-name: 'Pleis-backend-dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8DE223AF70D74AE6A51EEF16D991C7F0 }}
          package: .