name: Deploy Node.js API to Azure Web App - Pleis

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App (API — Pleis)
        uses: azure/webapps-deploy@v3
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: true
        with:
          app-name: 'Pleis'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D6B5A721CC1F4065BA303A78D3C5B578 }}
          package: .

      - name: Deploy to Azure Web App (Worker — Pleis-worker)
        uses: azure/webapps-deploy@v3
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: true
        with:
          app-name: 'Pleis-worker'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PLEIS_WORKER }}
          package: .
